# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Para proyectos Node.js (incluye pnpm)
    directory: "/"           # Carpeta donde está tu pnpm-lock.yaml
    schedule:
      interval: "weekly"     # Frecuencia de actualización
    allow:
      - dependency-type: "all"  # Puedes limitar a "direct" o "indirect"
    open-pull-requests-limit: 5 # Número máximo de PRs abiertos
